name: Release
on:
  push:
    branches:
      - alpha
      # - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Configure CI Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN_ACTION }}@github.com/${{ github.repository }}

      - name: npm install
        run: npm i

      - name: lerna version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: lerna version --yes

      - name: lerna publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: lerna publish from-git --dist-tag alpha --yes
